FROM container-registry.oracle.com/os/oraclelinux:9 AS builder
WORKDIR /opt

# Install Java 17
RUN curl https://download.oracle.com/java/17/archive/jdk-17.0.6_linux-aarch64_bin.tar.gz --output jdk-17.0.6.tar.gz \
#RUN curl https://download.oracle.com/java/17/archive/jdk-17.0.6_linux-x64_bin.tar.gz --output jdk-17.0.6.tar.gz \
    && tar xvfz jdk-17.0.6.tar.gz \
    && rm jdk-17.0.6.tar.gz \
    && mv jdk-17.0.6 java

ENV JAVA_HOME '/opt/java'
ENV GRADLE_USER_HOME '/opt/gradle'
ENV PATH "${PATH}:${JAVA_HOME}/bin"

# Build the application
WORKDIR /opt/app
COPY gradle gradle
COPY src src
COPY build.gradle build.gradle
COPY gradlew gradlew
COPY settings.gradle settings.gradle
RUN ./gradlew package

# ------------------------------------------------------------------------------

FROM container-registry.oracle.com/os/oraclelinux:9-slim
WORKDIR /opt

# Copy Java and application
COPY --from=builder /opt/java java
COPY --from=builder /opt/app/build/libs app

ENV JAVA_HOME '/opt/java'
ENV PATH "${PATH}:${JAVA_HOME}/bin"

EXPOSE 8080

ENTRYPOINT ["java", "--class-path", "/opt/app/*", "demo.Main"]
